# Generated by Django 4.1.10 on 2023-09-28 00:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItensOpcioanis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrao_imovel', models.CharField(max_length=20)),
                ('status_imovel', models.CharField(max_length=20)),
                ('tipo_imovel', models.CharField(max_length=20)),
                ('nome_construtora', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_empreendimento', models.CharField(max_length=100)),
                ('endereco_empreendimento', models.CharField(blank=True, max_length=300, null=True)),
                ('area_construida', models.CharField(max_length=10)),
                ('qtde_quartos', models.CharField(blank=True, max_length=10, null=True)),
                ('qtde_suites', models.CharField(blank=True, max_length=10, null=True)),
                ('qtde_vaga_garagem', models.CharField(blank=True, max_length=10, null=True)),
                ('item_opcinal_1', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_2', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_3', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_4', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_5', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_6', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_7', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_8', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_9', models.CharField(blank=True, max_length=30, null=True)),
                ('item_opcinal_10', models.CharField(blank=True, max_length=30, null=True)),
                ('info_complementares', models.TextField(blank=True, max_length=255, null=True)),
                ('anunciado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('imagem_1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_6', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_7', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_8', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_9', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_10', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_11', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_12', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_13', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_14', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
                ('imagem_15', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[1440, 480], upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_leads', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=13)),
                ('status_aberto', models.CharField(max_length=20)),
                ('status_leads', models.CharField(max_length=8)),
                ('data_recebimento', models.CharField(max_length=50)),
                ('ultimo_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vinculado', models.CharField(max_length=50)),
                ('whatsa_app', models.CharField(max_length=15)),
                ('img_perfil', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=[150, 150], upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='QtdeQuartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_quartos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qtdesuites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_suites', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QtdeVagaGaragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_vagas_garagem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_por', models.CharField(max_length=50)),
                ('data_atualizacao', models.CharField(max_length=15)),
                ('tag_google', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TagGoogleBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_por', models.CharField(max_length=50)),
                ('data_atualizacao', models.CharField(max_length=15)),
                ('tag_google_body', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tagmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_por', models.CharField(max_length=50)),
                ('data_atualizacao', models.CharField(max_length=15)),
                ('tag_meta', models.TextField(max_length=256)),
            ],
        ),
    ]
