# Generated by Django 4.1.6 on 2023-03-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agendamento', models.CharField(max_length=30)),
                ('data_evento', models.CharField(max_length=50)),
                ('data_termino', models.CharField(max_length=50)),
                ('data_agendamento', models.CharField(max_length=50)),
                ('user_agendamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('leads_atendimento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('anotacoes_atendimento', models.TextField(max_length=300)),
                ('data_inclusao_atendimento', models.CharField(max_length=15)),
                ('user_inclusao_atendimento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('atendimento_vinculados_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(max_length=100)),
                ('whatsapp_cliente', models.CharField(max_length=14)),
                ('cnpj_cpf_cliente', models.CharField(max_length=14)),
                ('endereco_cliente', models.CharField(max_length=100)),
                ('tel_fixo_cliente', models.CharField(max_length=13)),
                ('info_complementares', models.TextField(max_length=300)),
                ('data_inclusao_cliente', models.CharField(max_length=15)),
                ('user_inclusao_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_leads', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=11)),
                ('status_aberto', models.CharField(max_length=4)),
                ('status_leads', models.CharField(choices=[('FORTE', 'FORTE'), ('NEUTRO', 'NEUTRO'), ('FRACO', 'FRACO')], max_length=6)),
                ('data_recebimento', models.CharField(max_length=50)),
                ('ultimo_user', models.CharField(max_length=30)),
            ],
        ),
    ]
