# Generated by Django 4.1.10 on 2023-09-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_1',
            new_name='item_opcional_1',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_10',
            new_name='item_opcional_10',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_2',
            new_name='item_opcional_2',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_3',
            new_name='item_opcional_3',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_4',
            new_name='item_opcional_4',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_5',
            new_name='item_opcional_5',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_6',
            new_name='item_opcional_6',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_7',
            new_name='item_opcional_7',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_8',
            new_name='item_opcional_8',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='item_opcinal_9',
            new_name='item_opcional_9',
        ),
    ]
