# Generated by Django 4.1.6 on 2023-03-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status_leads',
            field=models.CharField(max_length=8),
        ),
    ]
