# Generated by Django 4.1.10 on 2023-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0002_rename_item_opcinal_1_landingpage_item_opcional_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='valor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
