# Generated by Django 4.1.6 on 2023-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0002_alter_leads_status_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status_aberto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leads',
            name='whatsapp',
            field=models.CharField(max_length=13),
        ),
    ]
