# Generated by Django 4.1.6 on 2023-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0003_tagmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_por', models.CharField(max_length=50)),
                ('data_atualizacao', models.CharField(max_length=15)),
                ('tag_google', models.CharField(max_length=256)),
            ],
        ),
    ]
