# Generated by Django 4.1.10 on 2023-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0004_remove_landingpage_valor_landingpage_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_facebook',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_instagram',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
