# Generated by Django 4.1.10 on 2023-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0004_alter_landingpage_info_complementares'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGoogleBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editado_por', models.CharField(max_length=50)),
                ('data_atualizacao', models.CharField(max_length=15)),
                ('tag_google_body', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='ItensDestaque',
        ),
    ]
