# Generated by Django 4.1.10 on 2023-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0005_taggooglebody_delete_itensdestaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggoogle',
            name='tag_google',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='taggooglebody',
            name='tag_google_body',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tagmeta',
            name='tag_meta',
            field=models.TextField(max_length=256),
        ),
    ]
