# Generated by Django 4.1.10 on 2023-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0006_alter_taggoogle_tag_google_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggoogle',
            name='tag_google',
            field=models.TextField(),
        ),
    ]
